stages: 
   - root_common_jar_build
   - common_jars_parallel_build
   - build
   - test
   - deploy

common_jar_x:
  stage: root_common_jar_build 
  script:
     - echo "build common jar x and push the common jar to GitLab"
     - sleep 3 

common_jar_y:
  stage: root_common_jar_build 
  script:
     - echo "build common jar y and push the common jar to GitLab"
     - sleep 30 

common_jar_z1:
  stage: common_jars_parallel_build 
  script:
     - echo "build common jar z1 and push the common jar to GitLab"
     - sleep 3 
  needs:
    - job: common_jar_x

common_jar_z2:
  stage: common_jars_parallel_build 
  script:
     - echo "build common jar z2 and push the common jar to GitLab"
     - sleep 30 
  needs:
    - job: common_jar_y

build_ui:   
  stage: build 
  script:
      - echo "build ui war"
      - sleep 10 
  needs:
    - job: common_jar_x


build_backend_api:   
  stage: build 
  script:  
     - echo "build backend api war"
     - sleep 20 
  needs:
    - job: common_jar_z1

test_ui:   
  stage: test 
  script:
     - echo "run unit test on ui "
     - sleep 10 
  needs:
    - job: build_ui

test_backend_api:   
  stage: test 
  script:  
     - echo "run unit test on backend api war"
     - sleep 20 
  needs:
    - job: build_backend_api

deploy_ui_to_stage_ENV:   
  stage: deploy 
  script:
     - echo "deploy ui war to stage ENV"
     - sleep 10      
  needs:
    - job: test_ui

deploy_backend_api_stage_ENV:   
  stage: deploy 
  script:  
     - echo "deploy backend api war to stage ENV"     
     - sleep 20      
  needs:
    - job: test_backend_api 