---
stages:
  - create file
  - show file
  - last stage

image: alpine

create:
  stage: create file
  script:
    - echo hello > some_file
    - mkdir some_dir
    - echo wow > some_dir/other_file
  artifacts:
    paths:
      - "some_file"
      - "some_dir"
    expire_in: "never"
    untracked: true

show:
  stage: show file
  script:
    - cat some_file
    - cat some_dir/other_file

last:
  stage: last stage
  dependencies: [create]
  script:
    - cat some_file

