version: '3.8'
services:

  gitlab-server:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab-server
    environment:
      GITLAB_ROOT_EMAIL: "admin@nadra"
      GITLAB_ROOT_PASSWORD: "nadra@123"
      GITLAB_OMNIBUS_CONFIG: |
        puma['worker_processes'] = 0 # disable cluster mode to avoid more memory usage
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    ports:
      - '8088:80'


  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    network_mode: 'host'

